# EMWM FreeBSD Makefile

PREFIX ?= /usr/local
MANDIR = $(PREFIX)/man
RCDIR = $(PREFIX)/X11
APPLRESDIR = $(PREFIX)/etc/X11/app-defaults

INCDIRS = -I./Xm -I/usr/local/include 
LIBDIRS = -L/usr/local/lib

CFLAGS += -Wall $(INCDIRS)

.include "common.mf"

install: common_install
