$ $XConsortium: Mwm.msg /main/3 1995/07/19 11:03:31 drk $
$set MS_errors
WMCDECOR_MSG_0 Insufficient memory for client window framing
WMCDECOR_MSG_1 Error reading Title Elements\n
WMERROR_MSG_0 I/O error on display:
WMFUNCTION_MSG_0 Cannot restart the window manager
WMFUNCTION_MSG_1 Unable to warp to unmanaged screen %d\n
WMGRAPHICS_MSG_0 Insufficient memory for graphics data
WMIDECOR_MSG_0 Could not make icon to go in icon box
WMIDECOR_MSG_1 Insufficient memory for icon creation
WMIPLACE_MSG_0 Insufficient memory to create icon box data
WMIMAGE_MSG_0 Invalid icon bitmap
WMIMAGE_MSG_1 Insufficient memory to bevel icon image
WMIMAGE_MSG_2 Can't find bitmap or pixmap file %s
WMINITWS_MSG_0 Could not open display.
WMINITWS_MSG_1 Insufficient memory for Screen data
WMINITWS_MSG_2 Another window manager is running on screen %d
WMINITWS_MSG_3 Unable to manage any screens on display.
WMINITWS_MSG_4 Cannot configure X connection
WMINITWS_MSG_5 
WMINITWS_MSG_6 Insufficient memory for Workspace data
WMINITWS_MSG_7 Insufficient memory for displayString
WMINITWS_MSG_8 Insufficient memory for window manager data
WMINITWS_MSG_9 Insufficient memory for screen names
WMMENU_MSG_0 Menu specification %s not found\n
WMMENU_MSG_1 Insufficient memory for menu %s\n
WMMENU_MSG_2 Insufficient memory for menu spec\n
WMMENU_MSG_3 Insufficient memory for menu item %s\n
WMMENU_MSG_4 Menu recursion detected for %s\n
WMPROPERTY_MSG_0 Insufficient memory for window management data
WMPROPERTY_MSG_1 Insufficient memory for window manager flags
WMPROTOCOL_MSG_0 Insufficient memory to XInternAtom _MOTIF_WM_QUERY_nn
WMPROTOCOL_MSG_1 Failed to own _MOTIF_WM_QUERY_nn selection
WMPROTOCOL_MSG_2 Lost _MOTIF_WM_QUERY_nn selection
WMPROTOCOL_MSG_3 Insufficient memory to convert _MOTIF_WM_QUERY_nn selection
WMPROTOCOL_MSG_4 Failed to own WM_nn selection
WMPROTOCOL_MSG_5 Got convert request from screen I don't manage!
WMPROTOCOL_MSG_6 Conversion request made for unknown target type
WMPROTOCOL_MSG_7 Conversion request received for unknown selection
WMRESPARSE_MSG_0 Cannot open configuration file
WMRESPARSE_MSG_1 Insufficient memory for menu accelerators
WMRESPARSE_MSG_2 Insufficient memory to get LANG environment variable.
WMRESPARSE_MSG_3 Insufficient memory for menu
WMRESPARSE_MSG_4 Expected '{' after menu name
WMRESPARSE_MSG_5 Insufficient memory for menu item label
WMRESPARSE_MSG_6 Insufficient memory for menu item
WMRESPARSE_MSG_7 Invalid mnemonic specification
WMRESPARSE_MSG_8 Insufficient memory for accelerator specification
WMRESPARSE_MSG_9 Invalid accelerator specification
WMRESPARSE_MSG_10 Insufficient memory
WMRESPARSE_MSG_11 Missing group specification
WMRESPARSE_MSG_12 Invalid group specification
WMRESPARSE_MSG_13 Invalid number specification
WMRESPARSE_MSG_14 Expected '{' after button set name
WMRESPARSE_MSG_15 Insufficient memory for button specification
WMRESPARSE_MSG_16 Invalid button specification
WMRESPARSE_MSG_17 Invalid button context
WMRESPARSE_MSG_18 Expected '{' after key set name
WMRESPARSE_MSG_19 Insufficient memory for key specification
WMRESPARSE_MSG_20 Invalid key specification
WMRESPARSE_MSG_21 Invalid key context
WMRESPARSE_MSG_22 %s: %s on line %d of configuration file \"%s\"\n
WMRESPARSE_MSG_23 %s: %s on line %d of specification string\n
WMRESPARSE_MSG_24 Insufficient memory for screen names
WMRESOURCE_MSG_0 failed to load font: %.100s
WMRESOURCE_MSG_1 cannot find an appropriate font: %.100s
WMRESOURCE_MSG_2 Insufficient memory for window manager data
WMRESOURCE_MSG_3 Key bindings %s not found, using builtin key bindings\n
WMRESOURCE_MSG_4 Button bindings %s not found, using builtin button bindings\n
WMSESSION_MSG_0 Session Manager Error: %s\n
WMSESSION_MSG_1 Session Manager Warning: %s\n
WMSESSION_MSG_2 Not enough memory to get text property.
WMSESSION_MSG_3 No client leader for subwindow. Setting clientLeader field.
WMSESSION_MSG_4 Not enough memory to create new orphan.
WMSESSION_MSG_5 Not enough memory to create new alien.
WMSESSION_MSG_6 Not enough memory to create new missingChild.
WMSESSION_MSG_7 Not enough memory to add new client leader.
WMSESSION_MSG_8 Not enought memory to create client list.
WMSESSION_MSG_9 Insufficient memory to XInternAtom WM_nn
WMSESSION_MSG_10 Failed to own WM_nn selection
WMSESSION_MSG_11 Missing child found mismarked client leader window.
WMWININFO_MSG_0 [XmbTextPropertyToTextList]:\n     Locale (%.100s) not supported. (Check $LANG).
WMWININFO_MSG_1 Insufficient memory for client data
WMWININFO_MSG_2 Couldn't make icon box
WMWININFO_MSG_3 mwm cannot convert property %.100s as clientTitle/iconTitle: XmbTextPropertyToTextList.
WMWININFO_MSG_4 insufficient memory to convert property %.100s as clientTitle/iconTitle: XmbTextPropertyToTextList.
WMWININFO_MSG_5 mwm receives unknown property as clientTitle/iconName : %.100s property ignored.
WMWININFO_MSG_6 Retrying - using builtin window menu\n
WMWINSTATE_MSG_0 Error: Divide by 0 in SetMwmIconInfo\n
WMWSM_MSG_0 Error: The selection owner does not understand the WSM protocol.\n
WMWSM_MSG_1 Error: No one owns selection.\n
WMWSM_MSG_2 Error: Owner of the WSM selection timed out.\n
WMWSM_MSG_3 Error: This request requires configuration format.\n
WMWSM_MSG_4 Error: This request cannot be sent after a config format request.\n
WMWSM_MSG_5 Internal Error: No reply received.\n
WMWSM_MSG_6 Unknown message type\n
WMWSM_MSG_7 Error occurred sending message to wsm.
CLIENTPROPS_MSG_0 %s: can't open %s.\n
CLIENTPROPS_MSG_1 Received %s message:  %s\n

$set MS_labels

WMICONBOX_MSG_0 \"Pack Icons\" _P  Shift Alt<Key>F7 f.pack_icons\n
